= Vision: {project-name}
Vorname Nachname <email@domain.org>; Vorname2 Nachname2 <email2@domain.org>; Vorname3 Nachname3 <email3@domain.org>
{localdatetime}
include::../_includes/default-attributes.inc.adoc[]
// Platzhalter für weitere Dokumenten-Attribute


== Einführung
Der Zweck dieses Dokuments ist es, die wesentlichen Bedarfe und Funktionalitäten des Systems {project-system-name} überblicksartig zu beschreiben. Der Fokus liegt auf den Fähigkeiten, die von Stakeholdern und adressierten Nutzern benötigt werden, und der Begründung dieser Bedarfe. Die Details, wie das System {project-system-name} diese Bedarfe erfüllt, werden durch User Stories im Product Backlog sowie dem UX-Konzept beschrieben.

=== Zweck
Der Zweck dieses Dokuments ist es, die wesentlichen Anforderungen an das System aus Sicht und mit den Begriffen der künftigen Anwender zu beschreiben.

=== Gültigkeitsbereich (Scope)
Dieses Visions-Dokument bezieht sich auf das System {Your cocktail at home}, das von <Team> entwickelt wird. Das System wird es <Zielkunde/Auftraggeber> erlauben, <Hauptfunktionen> zu nutzen, um damit <Vorteile> zu erreichen / <Aufgabe> zu erleichtern / <Problem> zu lösen.
Materialverwaltung, falls die Zutaten alle sind. Dadurch wissen die Kunden, welche Cocktails bestellen kann 

=== Definitionen, Akronyme und Abkürzungen
//Verweis passend zum Belegabgabe-Template se1_belegabgabe_t00.adoc
Siehe <<#glossary, Glossar>>.
//Siehe <<./glossary.adoc#glossary, Glossar>>.

=== Referenzen
(hier externe Verweise zu anderen Dokumenten, Quellen, Standards etc. einfügen, sofern notwendig)


== Positionierung

=== Fachliche Motivation
//Erläutern Sie kurz den Hintergrund, in dem das Projekt angesiedelt ist. Welches Problem soll gelöst werden, wie ist es entstanden? Welche Verbesserung wird angestrebt. Achten Sie darauf, eine fachliche (organisatorische, betriebswirtschaftliche) Perspektive einzunehmen.

=== Produktvision
//Eine Produktvision beschreibt das Einsatzziel der Anwendung und sorgt für ein gemeinsames Ziel und Verständnis für alle Beteiligten im Projekt. Geben Sie in knapper Form übersichtsartig die Positionierung der angestrebten Lösung im Vergleich zu verfügbaren Alternativen dar. Das folgende Format kann dazu verwendet werden:


[cols="1,3"]
|===
| Für | Cocktail-Liebhaber
| der / die | Cocktails online bestellt bekommen und zuhause selber zusammenstellen will
| ist das  | *Your cocktail at home*
| eine  | Online Alkohol Dienstleister
| der / die | Bestellung und Bezahlung der Cocktails online ermöglicht
| anders als | persönlichem Besuch an der Bar
| kann unser Produkt | nach persönlichem Geschmack individuell gestaltet werden und das Genießen zuhause mit Freunden und Familie ermöglichen
|===


//Beispiel
//[cols="1,3"]
//|===
//| Für | Studierende der HTWD
//| die | zu wenig Zeit in der Mittagspause zum Essen haben
//| ist   | Flying Burger
//| ein  | Lieferdient für Burger
//| der  | per Drohne liefert
//| anders als | landgestützte Lieferdienste
//| kann unser Produkt |  durchs Fenster direkt in den Hörsaal liefern.
//|===

== Stakeholder Beschreibungen

=== Zusammenfassung der Stakeholder

[%header, cols="1,3,3"]
|===
| Name | Beschreibung der Motivation| Verantwortlichkeiten

| _Kunde_: Bar-Betreiber

_Nutzer_: Cocktail-Besteller, Bar-Besucher

_Gesetzgeber_: Hygienevorschriften, DSGVO, Jugendschutz

_Lieferer_: Lieferdienst
_Zahlungsdienstleister_: technische, inhaltliche, rechtliche Bedingungen 

| Die Besteller wollen für bestimmte Anlässe special Cocktails bekommen
| _Kunde_: beanfrage Entwicklung

_Nutzer_: Cocktailbesteller

_Gesetzgeber_: Gesetzbeinhaltung prüfen

_Lieferdienst_: Liefert die Produkte

_Zahlungsdienstleister_: Es ist eine Schnittstelle zwischen Kunden und Dienstleistanbieter (Barbetreiber)

Der Stakeholder bestellt das angebotene Online Item und bezahlt dafür. Sie sorgen dafür, dass die Dresdner-Bar den Online Shop einfach wie möglich gestaltet, aktuelle Angebote per Email sendet und Storniermöglichkeiten nach der Bestellung anbietet. Schließlich sollen die bestellten Produkte per Lieferung gesendet werden. 
|===

Die Verfeinerung der Stakeholder, die das System benutzen, wird im UX-Konzept mittels Personas vorgenommen.


== Produktüberblick

=== Bedarfe und Hauptfunktionen
//Vermeiden Sie Angaben zum Entwurf. Nennen wesentliche Features (Produktmerkmale) auf allgemeiner Ebene. Fokussieren Sie sich auf die benötigten Fähigkeiten des Systems und warum (nicht wie!) diese realisiert werden sollen. Geben Sie die von den Stakeholdern vorgegebenen Prioritäten an.

[%header, cols="4,1,4,1"]
|===
| Bedarf | Priorität | Features / Funktionen | Geplantes Release
|  |  | Lieferdienst | xx.xx.xxxx
| individuelle Cocktails | 1 | Auswahl der Zutaten zur eigenen Kreationen per Webseite  | xx.xx.xxxx
| Kunden benutzen verschiedene Banksysteme | 3 | verschiedene Bezahlmöglichkeiten| xx.xx.xxxx
| Kunden wollen einen Nachweis/Bestätigung der Bestellung bekommen | xx | Bestellbestätigung per Email | xx.xx.xxxx
| xx | xx | Bestellhistorie mit Status| xx.xx.xxxx
| Kunden wollen die Webseite möglichst einfach und schnell benutzen/Barrierefreihet | xx | einfache Benutzeroberfläche | xx.xx.xxxx
| Treukunden wollen special Angebote bekommen | xx | special Angebote per Email schicken | xx.xx.xxxx
| Agil/ | xx | keine Mindest- und Höchstbestellmenge | xx.xx.xxxx
| xx | xx | keine Rechnung -> Sperrung der Bestellung | xx.xx.xxxx
| xx | xx | Stammkunde -> Besondere Konditionen (Rabatt, special Angebote ) | xx.xx.xxxx
|===


=== Zusätzliche Produktanforderungen
//Zutreffendes angeben, nicht zutreffendes streichen oder auskommentieren
Hinweise:

. Führen Sie die wesentlichen anzuwendenden Standards, Hardware oder andere Plattformanforderungen, Leistungsanforderungen und Umgebungsanforderungen auf
. Definieren Sie grob die Qualitätsanforderungen für Leistung, Robustheit, Ausfalltoleranz, Benutzbarkeit und ähnliche Merkmale, die Qualitätsanforderungen an das geplante Produkt beschreiben.
. Notieren Sie alle Entwurfseinschränkungen, externe Einschränkungen, Annahmen oder andere Abhängigkeiten, die wenn Sie geändert werden, das Visions-Dokument beeinflussen. Ein Beispiel wäre die Annahme, dass ein bestimmtes Betriebssystem für die vom System erforderliche Hardware verfügbar ist. Ist das Betriebssystem nicht verfügbar, muss das Visions-Dokument angepasst werden.
. Definieren Sie alle Dokumentationsanforderugen, inkl. Benutzerhandbücher, Onlinehilfe, Installations-, Kennzeichnungs- und Auslieferungsanforderungen.
. Definieren Sie die Priorität für diese zusätzlichen Produktanforderungen. Ergänzen Sie, falls sinnvoll, Angaben zu Stabilität, Nutzen, Aufwand und Risiko für diese Anforderungen.

[%header, cols="4,1,1"]
|===
| Anforderung | Priorität | Geplantes Release
| xx | xx | xx
|===
